name: GitHub Metrics

on:
  schedule: [{ cron: "0 0 * * *" }] # Daily at 9 AM KST (00:00 UTC)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: ForTemLabs
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Seoul
          committer_message: "Update metrics [Skip GitHub Action]"

          # Language stats
          plugin_languages: yes
          plugin_languages_ignored: html,css
          plugin_languages_limit: 8

          # Activity stats
          plugin_traffic: yes
          plugin_lines: yes
          plugin_followup: yes

          # Repository stats
          plugin_repositories: yes
          plugin_repositories_featured: ForTemLabs/fortem,ForTemLabs/sdk-js,ForTemLabs/fortem-sdk-unity,ForTemLabs/fortem-docs
